### ISSUE TITLE
no way to run go test -v

### ISSUE THREAD

**Issue by phoet** [Luzifer/rconfig#1]
when running `go test` with the verbose flag `-v`, it's trying to parse this unknown option and raises an error. is there some known workaround for this? or some way to configure it to be more forgiving?

```
DB_PASSWORD=jimdo go test -v app/*.go
=== RUN TestPresign
unknown shorthand flag: 't' in -test.v=true
Usage of /var/folders/vg/_nm_gr392nzcd6cvcs_dnz1w0000gn/T/go-build663204920/command-line-arguments/_test/app.test:
      --db-database="xyz": The name of the MYSQL database
      [...]
exit status 2
```

**Comment by Luzifer** [comment]
Additional information: `rconfig.Parse()` is called inside of a test function which gets compiled and in case of `test -v` passed a parameter `-test.v=true`. That flag causes the `pflag` library to fail because there are (most likely) no shorthands `-t, -e, -s, -., -v`…

**Comment by Luzifer** [comment]
@nightlyone ping

**Comment by nightlyone** [comment]
@phoet / @Luzifer could you give a small, self-container reproducer for this (e.g. one `main.go` and one `main_test.go`) ?

Reason: I guess the recommendation of using `main.init` instead of `main.main` to trigger `rconfig.Parse()` is the culprit.

Function parsing `os.Args` should never be called outside `main.main`.

**Comment by nightlyone** [comment]
Should work now for since Go 1.6, because test parameters are parsed before parameters of package to be tested.

I would still change the recommendation to trigger parsing of `os.Args` only inside `main.main` for better program clarity.

**Comment by Luzifer** [comment]
Indeed, works now. Tested with Go 1.7:

``` bash
# cat main.go
package main

import (
        "fmt"

        "github.com/Luzifer/rconfig"
)

var (
        cfg = struct {
                Testparm string `flag:"myparam" default:"Hello World"`
        }{}

        foobar = "bar"
)

func init() {
        rconfig.Parse(&cfg)
}

func main() {
        fmt.Println(cfg.Testparm)
}

# cat main_test.go
package main

import "testing"

func TestFoobar(t *testing.T) {
        if foobar != "bar" {
                t.Fail()
        }
}

# go run main.go
Hello World

# go test
PASS
ok      rconfigtest     0.003s

# go test -v
=== RUN   TestFoobar
--- PASS: TestFoobar (0.00s)
PASS
ok      rconfigtest     0.003s
```
