### ISSUE TITLE
Error while go getting

### ISSUE THREAD

**Issue by seiffert** [Luzifer/rconfig#2]
I'm not sure whether this is actually an issue of this project or if I'm doing something wrong. Since `go get` returns with exit code 1, I'm opening an issue for this:

```
$ go get gopkg.in/luzifer/rconfig.v1
package gopkg.in/luzifer/rconfig.v1: code in directory /Users/seiffert/Projects/src/gopkg.in/luzifer/rconfig.v1 expects import "github.com/Luzifer/rconfig"
$ echo $?
1
```

For me, it looks like there's an issue with the [annotated](https://github.com/Luzifer/rconfig/blob/da841b2cc9b51693faecb9174fafb3f4477f1c43/config.go#L4) canonical import path `github.com/Luzifer/rconfig`. Is it possible that the usage of gopgk requires packages to either not declare a custom import path or use the `gopkg.in/...` one?

**Comment by Luzifer** [comment]
Thanks for reporting this. 

The error has been solved by removing the canonical import path. This way the library can be used both ways, through pkg.in and directly from GitHub using the master.
